# Setup
title:        REST2EJB
tagline:      A Complete REST Client with built-in EJB client support
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Dheerendra Soni
  url:        https://github.com/DheerendraSoni

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
